# Taller Pandas — Ventas Librerías Culturales

In [1]:
import pandas as pd
import numpy as np

## 1.Lectura y Verificación de Importación

In [20]:
#Carga el archivo ventas_libreria_cultural.csv en un DataFrame denominado df_libros evitando la adición de columnas índices innecesarias.
df_libros = pd.read_csv("ventas_libreria_cultural.csv", index_col=False)
df_libros

,ID_Transaccion,Sucursal,Genero_Libro,Formato,Precio_Lista,Unidades_Vendidas,Descuento_Aplicado,Metodo_Pago
0,LIB-9001,Galería de Arte,Ensayo Científico,Bolsillo,72000.0,1,0.00,Efectivo
1,LIB-9002,Centro Histórico,Historia y Crítica,Edición Ilustrada,45000.0,1,0.10,Efectivo
2,LIB-9003,Terminal,Novela Gráfica,Bolsillo,115000.0,1,0.00,Tarjeta Débito
3,LIB-9004,Galería de Arte,Ensayo Científico,Tapa Blanda,45000.0,5,0.00,Tarjeta Crédito
4,LIB-9005,Centro Histórico,Literatura Clásica,Tapa Blanda,32000.0,2,0.05,Tarjeta Crédito
...,...,...,...,...,...,...,...,...
1007,LIB-9168,Centro Histórico,Ensayo Científico,Tapa Dura,89000.0,6,0.00,Tarjeta Débito
1008,LIB-9169,Terminal,Novela Gráfica,Tapa Blanda,72000.0,2,0.05,Tarjeta Crédito
1009,LIB-9170,Zona Rosa,Novela Gráfica,Tapa Blanda,72000.0,2,NaN,Transferencia QR
1010,LIB-9171,Terminal,Ensayo Científico,Bolsillo,72000.0,2,0.00,Tarjeta Crédito
1011,LIB-9172,Campus Universitario,Ciencia Ficción,Tapa Dura,72000.0,5,0.10,Tarjeta Crédito

## 2. Selección Unidimensional y Multivariable:

In [21]:
#Extrae la columna Genero_Libro como una Serie de Pandas y genera una nueva tabla que contenga simultáneamente Sucursal, 
# Formato y Precio_Lista.
genero = df_libros['Genero_Libro']
print(type(genero))
tabla = df_libros[['Sucursal', 'Formato', 'Precio_Lista']]
tabla.head(2)

<class 'pandas.Series'>

           Sucursal            Formato  Precio_Lista
0   Galería de Arte           Bolsillo       72000.0
1  Centro Histórico  Edición Ilustrada       45000.0

## 3.Acceso por Etiqueta (loc)

In [23]:
# Consulta todos los campos de la transacción registrada exactamente en la fila con índice 310 utilizando el método .
df_libros.loc[310]

ID_Transaccion                    LIB-9311
Sucursal              Campus Universitario
Genero_Libro            Historia y Crítica
Formato                          Tapa Dura
Precio_Lista                       58000.0
Unidades_Vendidas                        1
Descuento_Aplicado                     0.1
Metodo_Pago                 Tarjeta Débito
Name: 310, dtype: object

## 4. Tratamiento de Redundancias

In [5]:
#Aplica .drop_duplicates() para suprimir las filas repetidas y confirmar el tamaño limpio de la base de datos.
print('Antes:', df_libros.shape)
df_libros = df_libros.drop_duplicates()
print('Después:', df_libros.shape)

Antes: (1012, 8)
Después: (1000, 8)

## 5. Filtrado por Volumen de Compra

In [6]:
#Realiza un filtro booleano simple que seleccione únicamente las compras mayoristas donde Unidades_Vendidas > 3.
df_libros[df_libros['Unidades_Vendidas'] > 3]
df_libros.head(13)

,ID_Transaccion,Sucursal,Genero_Libro,Formato,Precio_Lista,Unidades_Vendidas,Descuento_Aplicado,Metodo_Pago
0,LIB-9001,Galería de Arte,Ensayo Científico,Bolsillo,72000.0,1,0.00,Efectivo
1,LIB-9002,Centro Histórico,Historia y Crítica,Edición Ilustrada,45000.0,1,0.10,Efectivo
2,LIB-9003,Terminal,Novela Gráfica,Bolsillo,115000.0,1,0.00,Tarjeta Débito
3,LIB-9004,Galería de Arte,Ensayo Científico,Tapa Blanda,45000.0,5,0.00,Tarjeta Crédito
4,LIB-9005,Centro Histórico,Literatura Clásica,Tapa Blanda,32000.0,2,0.05,Tarjeta Crédito
5,LIB-9006,Zona Rosa,Literatura Clásica,Edición Ilustrada,89000.0,4,0.00,Transferencia QR
6,LIB-9007,Terminal,Ensayo Científico,Tapa Blanda,45000.0,3,NaN,Tarjeta Débito
7,LIB-9008,Zona Rosa,Ensayo Científico,Tapa Blanda,58000.0,3,0.00,Tarjeta Débito
8,LIB-9009,Terminal,Ciencia Ficción,Edición Ilustrada,58000.0,5,0.00,Tarjeta Crédito
9,LIB-9010,Zona Rosa,Historia y Crítica,Edición Ilustrada,32000.0,5,0.00,Transferencia QR
10,LIB-9011,Terminal,Ensayo Científico,Bolsillo,58000.0,4,0.00,Tarjeta Débito
11,LIB-9012,Centro Histórico,Novela Gráfica,Bolsillo,45000.0,3,0.10,Tarjeta Crédito
12,LIB-9013,Campus Universitario,Novela Gráfica,Bolsillo,72000.0,5,NaN,Tarjeta Débito

## 6. Filtrado Categórico con .isin()

In [24]:
#Recupera todas las operaciones registradas exclusivamente en las sucursales Campus Universitario y Galería de Arte.
df_libros[df_libros['Sucursal'].isin(['Campus Universitario', 'Galería de Arte'])].head()

,ID_Transaccion,Sucursal,Genero_Libro,Formato,Precio_Lista,Unidades_Vendidas,Descuento_Aplicado,Metodo_Pago
0,LIB-9001,Galería de Arte,Ensayo Científico,Bolsillo,72000.0,1,0.0,Efectivo
3,LIB-9004,Galería de Arte,Ensayo Científico,Tapa Blanda,45000.0,5,0.0,Tarjeta Crédito
12,LIB-9013,Campus Universitario,Novela Gráfica,Bolsillo,72000.0,5,NaN,Tarjeta Débito
13,LIB-9014,Campus Universitario,Novela Gráfica,Tapa Dura,45000.0,1,NaN,Tarjeta Crédito
15,LIB-9016,Galería de Arte,Historia y Crítica,Bolsillo,45000.0,4,0.0,Tarjeta Débito

## 7. Filtrado por Rango de Precios (between)

In [25]:
#Utiliza .between() para aislar las compras donde el Precio_Lista se ubique entre $45,000 y $75,000 inclusive.
df_libros[df_libros['Precio_Lista'].between(45000, 75000)].head(10)

,ID_Transaccion,Sucursal,Genero_Libro,Formato,Precio_Lista,Unidades_Vendidas,Descuento_Aplicado,Metodo_Pago
0,LIB-9001,Galería de Arte,Ensayo Científico,Bolsillo,72000.0,1,0.0,Efectivo
1,LIB-9002,Centro Histórico,Historia y Crítica,Edición Ilustrada,45000.0,1,0.1,Efectivo
3,LIB-9004,Galería de Arte,Ensayo Científico,Tapa Blanda,45000.0,5,0.0,Tarjeta Crédito
6,LIB-9007,Terminal,Ensayo Científico,Tapa Blanda,45000.0,3,NaN,Tarjeta Débito
7,LIB-9008,Zona Rosa,Ensayo Científico,Tapa Blanda,58000.0,3,0.0,Tarjeta Débito
8,LIB-9009,Terminal,Ciencia Ficción,Edición Ilustrada,58000.0,5,0.0,Tarjeta Crédito
10,LIB-9011,Terminal,Ensayo Científico,Bolsillo,58000.0,4,0.0,Tarjeta Débito
11,LIB-9012,Centro Histórico,Novela Gráfica,Bolsillo,45000.0,3,0.1,Tarjeta Crédito
12,LIB-9013,Campus Universitario,Novela Gráfica,Bolsillo,72000.0,5,NaN,Tarjeta Débito
13,LIB-9014,Campus Universitario,Novela Gráfica,Tapa Dura,45000.0,1,NaN,Tarjeta Crédito

## 8. Consultas Directas con .query()

In [ ]:
#Realiza una búsqueda mediante .query() para extraer las ventas efectuadas
# con Metodo_Pago == 'Transferencia QR' en las que Unidades_Vendidas >= 2.
df_libros.query("Metodo_Pago == 'Transferencia QR' and Unidades_Vendidas >= 2").head(10)

,ID_Transaccion,Sucursal,Genero_Libro,Formato,Precio_Lista,Unidades_Vendidas,Descuento_Aplicado,Metodo_Pago
5,LIB-9006,Zona Rosa,Literatura Clásica,Edición Ilustrada,89000.0,4,0.0,Transferencia QR
9,LIB-9010,Zona Rosa,Historia y Crítica,Edición Ilustrada,32000.0,5,0.0,Transferencia QR
18,LIB-9019,Centro Histórico,Novela Gráfica,Edición Ilustrada,72000.0,2,0.0,Transferencia QR
20,LIB-9021,Centro Histórico,Novela Gráfica,Bolsillo,58000.0,6,0.0,Transferencia QR
22,LIB-9023,Centro Histórico,Ensayo Científico,Bolsillo,58000.0,2,0.0,Transferencia QR
24,LIB-9025,Campus Universitario,Historia y Crítica,Edición Ilustrada,58000.0,4,NaN,Transferencia QR
27,LIB-9028,Terminal,Novela Gráfica,Tapa Dura,58000.0,3,0.0,Transferencia QR
35,LIB-9036,Centro Histórico,Literatura Clásica,Tapa Blanda,32000.0,5,0.1,Transferencia QR
36,LIB-9037,Zona Rosa,Literatura Clásica,Tapa Dura,32000.0,5,0.0,Transferencia QR
41,LIB-9042,Centro Histórico,Ciencia Ficción,Tapa Dura,32000.0,2,0.0,Transferencia QR

## 9. Filtrado Compuesto con Métodos de Texto

In [10]:
#Construye una condición booleana con & que localice los libros cuyo Genero_Libro inicie con "Ensayo" mediante .str.startswith() 
# y cuyo Precio_Lista sea superior a $50,000.
filtro = df_libros['Genero_Libro'].str.startswith('Ensayo') & (df_libros['Precio_Lista'] > 50000)
df_libros[filtro].head(10)

,ID_Transaccion,Sucursal,Genero_Libro,Formato,Precio_Lista,Unidades_Vendidas,Descuento_Aplicado,Metodo_Pago
0,LIB-9001,Galería de Arte,Ensayo Científico,Bolsillo,72000.0,1,0.0,Efectivo
7,LIB-9008,Zona Rosa,Ensayo Científico,Tapa Blanda,58000.0,3,0.0,Tarjeta Débito
10,LIB-9011,Terminal,Ensayo Científico,Bolsillo,58000.0,4,0.0,Tarjeta Débito
22,LIB-9023,Centro Histórico,Ensayo Científico,Bolsillo,58000.0,2,0.0,Transferencia QR
49,LIB-9050,Campus Universitario,Ensayo Científico,Bolsillo,58000.0,2,0.1,Efectivo
53,LIB-9054,Campus Universitario,Ensayo Científico,Edición Ilustrada,89000.0,3,0.0,Tarjeta Débito
56,LIB-9057,Terminal,Ensayo Científico,Edición Ilustrada,89000.0,1,0.0,Tarjeta Débito
85,LIB-9086,Centro Histórico,Ensayo Científico,Edición Ilustrada,115000.0,5,0.0,Transferencia QR
90,LIB-9091,Galería de Arte,Ensayo Científico,Tapa Dura,58000.0,3,0.1,Tarjeta Débito
91,LIB-9092,Centro Histórico,Ensayo Científico,Tapa Dura,58000.0,4,0.0,Tarjeta Débito

## 10. Imputación Estratificada de Faltantes

In [11]:
#Rellena los valores ausentes (NaN) en la columna Precio_Lista calculando el promedio aritmético de dicha variable, e imputa los nulos
#  de Descuento_Aplicado con un valor constante de 0.0 mediante .fillna().
df_libros = df_libros.fillna({
    'Precio_Lista': df_libros['Precio_Lista'].mean(),
    'Descuento_Aplicado': 0.0
})
df_libros.isna().sum()

ID_Transaccion        0
Sucursal              0
Genero_Libro          0
Formato               0
Precio_Lista          0
Unidades_Vendidas     0
Descuento_Aplicado    0
Metodo_Pago           0
dtype: int64

## 11. Transformación con Funciones y Creación de Columnas (apply)

In [12]:
#Define una función de Python que calcule el subtotal neto a pagar: (Precio_Lista * (1 - Descuento_Aplicado)) * Unidades_Vendidas. Luego, 
# aplícala con .apply() para crear la columna Total_Venta.
def calcular_total(fila):
    return (fila['Precio_Lista'] * (1 - fila['Descuento_Aplicado'])) * fila['Unidades_Vendidas']

df_libros['Total_Venta'] = df_libros.apply(calcular_total, axis=1)
df_libros.head()

,ID_Transaccion,Sucursal,Genero_Libro,Formato,Precio_Lista,Unidades_Vendidas,Descuento_Aplicado,Metodo_Pago,Total_Venta
0,LIB-9001,Galería de Arte,Ensayo Científico,Bolsillo,72000.0,1,0.00,Efectivo,72000.0
1,LIB-9002,Centro Histórico,Historia y Crítica,Edición Ilustrada,45000.0,1,0.10,Efectivo,40500.0
2,LIB-9003,Terminal,Novela Gráfica,Bolsillo,115000.0,1,0.00,Tarjeta Débito,115000.0
3,LIB-9004,Galería de Arte,Ensayo Científico,Tapa Blanda,45000.0,5,0.00,Tarjeta Crédito,225000.0
4,LIB-9005,Centro Histórico,Literatura Clásica,Tapa Blanda,32000.0,2,0.05,Tarjeta Crédito,60800.0

## 12. Renombrado y Reorganización de Variables

In [13]:
#Renombra Genero_Libro a Categoria y Descuento_Aplicado a Descuento usando .rename(). Posteriormente, reordena
#  las columnas colocando ID_Transaccion y Total_Venta al inicio de la estructura.
df_libros = df_libros.rename(columns={'Genero_Libro': 'Categoria', 'Descuento_Aplicado': 'Descuento'})
primeras = ['ID_Transaccion', 'Total_Venta']
df_libros = df_libros[primeras + [c for c in df_libros.columns if c not in primeras]]
df_libros.head()

,ID_Transaccion,Total_Venta,Sucursal,Categoria,Formato,Precio_Lista,Unidades_Vendidas,Descuento,Metodo_Pago
0,LIB-9001,72000.0,Galería de Arte,Ensayo Científico,Bolsillo,72000.0,1,0.00,Efectivo
1,LIB-9002,40500.0,Centro Histórico,Historia y Crítica,Edición Ilustrada,45000.0,1,0.10,Efectivo
2,LIB-9003,115000.0,Terminal,Novela Gráfica,Bolsillo,115000.0,1,0.00,Tarjeta Débito
3,LIB-9004,225000.0,Galería de Arte,Ensayo Científico,Tapa Blanda,45000.0,5,0.00,Tarjeta Crédito
4,LIB-9005,60800.0,Centro Histórico,Literatura Clásica,Tapa Blanda,32000.0,2,0.05,Tarjeta Crédito

## 13. Agrupación y Métricas de Facturación por Sucursal

In [14]:
# Agrupa los registros por Sucursal y calcula simultáneamente el promedio de Precio_Lista y
#  la suma global acumulada de Total_Venta mediante el método .agg().
df_libros.groupby('Sucursal').agg({'Precio_Lista': 'mean', 'Total_Venta': 'sum'}).round(1)

                      Precio_Lista  Total_Venta
Sucursal
Campus Universitario       57630.0   38968829.9
Centro Histórico           57419.0   35594598.1
Galería de Arte            55927.4   40988247.8
Terminal                   58516.1   33656043.3
Zona Rosa                  55668.5   33413736.7

## 14. Métricas de Rango Personalizadas

In [15]:
# Diseña una función personalizada llamada rango (series.max() - series.min()) y
#  aplícala con .agg() sobre las columnas Precio_Lista y Total_Venta tras agrupar por Formato.
def rango(series):
    return series.max() - series.min()

df_libros.groupby('Formato').agg({'Precio_Lista': rango, 'Total_Venta': rango})

                   Precio_Lista  Total_Venta
Formato
Bolsillo                83000.0     503600.0
Edición Ilustrada       83000.0     544600.0
Tapa Blanda             83000.0     662800.0
Tapa Dura               83000.0     664400.0

## 15. Agrupamiento multinivel

In [16]:
#Realiza una agrupación combinada por Sucursal y Categoria, obteniendo un resumen que detalle el
# promedio del Total_Venta y la suma global de Unidades_Vendidas para cada combinación.
df_libros.groupby(['Sucursal', 'Categoria']).agg({'Total_Venta': 'mean', 'Unidades_Vendidas': 'sum'}).round(2).head(100)

                                         Total_Venta  Unidades_Vendidas
Sucursal             Categoria
Campus Universitario Ciencia Ficción       151050.56                121
                     Ensayo Científico     185033.97                173
                     Historia y Crítica    213691.00                174
                     Literatura Clásica    195582.72                111
                     Novela Gráfica        192083.78                134
Centro Histórico     Ciencia Ficción       167983.42                118
                     Ensayo Científico     202911.70                104
                     Historia y Crítica    200169.17                181
                     Literatura Clásica    181721.87                118
                     Novela Gráfica        179066.40                138
Galería de Arte      Ciencia Ficción       163494.51                148
                     Ensayo Científico     158508.53                161
                     Historia y Crítica    210753.06                193
                     Literatura Clásica    209879.41                125
                     Novela Gráfica        193224.36                140
Terminal             Ciencia Ficción       196755.08                136
                     Ensayo Científico     182576.86                106
                     Historia y Crítica    187277.34                150
                     Literatura Clásica    167968.78                112
                     Novela Gráfica        157931.05                102
Zona Rosa            Ciencia Ficción       169218.43                164
                     Ensayo Científico     190466.67                 92
                     Historia y Crítica    177175.43                134
                     Literatura Clásica    173039.71                124
                     Novela Gráfica        164066.62                133